=== Alexandersimanovich/AT2019-03-12/src/by/it/romanova/at15/dtd_sites.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT sites (site)+>
<!ELEMENT site (pages)>
<!ATTLIST site url PCDATA #REQUIRED>
<!ELEMENT pages (page)+>
<!ELEMENT page (name,element)>
<!ATTLIST page id PCDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT element (#PCDATA)>
<!ATTLIST element element_id CDATA #REQUIRED>

=== Alexandersimanovich/AT2019-03-12/src/by/it/romanova/at15/sites+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE sites SYSTEM "dtd_sites.dtd" >
<sites>
    <site url="http://romanova.by">
        <pages>
            <page id="0001">
                <name>First Page</name>
                <element element_id="10001">
                    page header
                </element>
                <element element_id="10002">
                    page body
                </element>
                <element element_id="10003">
                    page footer
                </element>
            </page>
            <page id="0002">
                <name>Second page</name>
                <element element_id="20001">
                    page header
                </element>
                <element element_id="20002">
                    text field
                </element>
                <element element_id="20003">
                    text button
                </element>
            </page>
        </pages>
    </site>
    <site url="http://at2019.by">
        <pages>
            <page id="0001">
                <name>Info Page</name>
                <element element_id="10001">
                    page header
                </element>
                <element element_id="10002">
                    page content
                </element>
                <element element_id="10003">
                    page footer
                </element>
            </page>
            <page id="0002">
                <name>Second page</name>
                <element element_id="20001">
                    page header
                </element>
                <element element_id="20002">
                    text field
                </element>
                <element element_id="20003">
                    text button
                </element>
            </page>
        </pages>
    </site>
</sites>
