=== Alexandersimanovich/AT2019-03-12/src/by/it/romanova/at15/xsd_sites.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://at15.by.it.romanova"
        xmlns:tns="http://at15.by.it.romanova"
        elementFormDefault="qualified">
  <element name="sites" type="tns:sitesType"/>
  <complexType name="elementType">
    <simpleContent>
      <extension base="string">
        <attribute type="string" name="element_id" use="optional"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="pageType">
    <sequence>
      <element name="name">
        <simpleType>
          <restriction base="string">
            <enumeration value="First Page"/>
            <enumeration value="Second page"/>
            <enumeration value="Info Page"/>
          </restriction>
        </simpleType>
      </element>

      <element type="tns:elementType" name="element" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
    <attribute type="string" name="id"/>
  </complexType>
  <complexType name="pagesType">
    <sequence>
      <element type="tns:pageType" name="page" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>
  <complexType name="siteType">
    <sequence>
      <element type="tns:pagesType" name="pages"/>
    </sequence>
    <attribute type="string" name="url"/>
  </complexType>
  <complexType name="sitesType">
    <sequence>
      <element type="tns:siteType" name="site" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>
</schema>

=== Alexandersimanovich/AT2019-03-12/src/by/it/romanova/at15/sites+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<sites xmlns="http://at15.by.it.romanova"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation= "http://at15.by.it.romanova xsd_sites.xsd">
    <site url="http://romanova.by">
        <pages>
            <page id="0001">
                <name>First Page</name>
                <element element_id="10001">
                    page header
                </element>
                <element element_id="10002">
                    page body
                </element>
                <element element_id="10003">
                    page footer
                </element>
            </page>
            <page id="0002">
                <name>Second page</name>
                <element element_id="20001">
                    page header
                </element>
                <element element_id="20002">
                    text field
                </element>
                <element element_id="20003">
                    text button
                </element>
            </page>
        </pages>
    </site>
    <site url="http://at2019.by">
        <pages>
            <page id="0001">
                <name>Info Page</name>
                <element element_id="10001">
                    page header
                </element>
                <element element_id="10002">
                    page content
                </element>
                <element element_id="10003">
                    page footer
                </element>
            </page>
            <page id="0002">
                <name>Second page</name>
                <element element_id="20001">
                    page header
                </element>
                <element element_id="20002">
                    text field
                </element>
                <element element_id="20003">
                    text button
                </element>
            </page>
        </pages>
    </site>
</sites>
