=== Alexandersimanovich/AT2019-03-12/src/by/it/tsyhanova/at15/sites.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://bean.at16.tsyhanova.it.by"
        xmlns:tns="http://bean.at16.tsyhanova.it.by"
        elementFormDefault="qualified">
    <element name="sites">
        <complexType>
            <sequence>
                <element name="site"
                         type="tns:typeSite"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="typeSite">
        <sequence>
            <element name="pages"
                     type="tns:typePages"/>
        </sequence>
        <attribute name="url" type="string"/>
    </complexType>
    <complexType name="typePages">
        <sequence>
            <element name="page"
                     type="tns:typePage"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="typePage">
        <sequence>
            <element name="uri" type="string"/>
            <element name="elements"
                     type="tns:typeElements"
                     minOccurs="1"
                     maxOccurs="1"/>
        </sequence>
        <attribute name="title" type="string"/>
    </complexType>
    <complexType name="typeElements">
        <sequence>
            <element name="element"
                     type="tns:typeElement"
                     minOccurs="1"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="typeElement">
        <simpleContent>
            <extension base="string">
                <attribute name="name" type="string"></attribute>
            </extension>
        </simpleContent>
    </complexType>
    <simpleType name="name">
        <restriction base="string">
            <enumeration value="head" />
            <enumeration value="body" />
            <enumeration value="form" />
        </restriction>
    </simpleType>
</schema>

=== Alexandersimanovich/AT2019-03-12/src/by/it/tsyhanova/at15/sites+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<sites xmlns="http://bean.at16.tsyhanova.it.by"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://bean.at16.tsyhanova.it.by sites.xsd">
    <site url="http://it.by">
        <pages>
            <page title="Main Page">
                <uri>/index</uri>
                <elements>
                    <element name="head">
                        head for main
                    </element>
                    <element name="body">
                        body for main
                    </element>
                </elements>
            </page>
            <page title="Login Page">
                <uri>/login</uri>
                <elements>
                    <element name="head">
                        head for login
                    </element>
                    <element name="form">
                        body for login
                    </element>
                </elements>
            </page>
        </pages>
    </site>
    <site url="http://ya.by">
        <pages>
            <page title="Index Page">
                <uri>/index</uri>
                <elements>
                    <element name="head">
                        Search Yandex
                    </element>
                    <element name="form">
                        Search form
                    </element>
                </elements>
            </page>
            <page title="Search Result">
                <uri>/result</uri>
                <elements>
                    <element name="head">
                       Search result Yandex
                    </element>
                    <element name="content">
                        Some content
                    </element>
                </elements>
            </page>
        </pages>
    </site>
</sites>

=== Alexandersimanovich/AT2019-03-12/src/by/it/agrinkevich/at15/sites+xsd.xml
<?xml version="1.0" encoding="utf-8" ?>
<sites xmlns="http://bean.at16.agrinkevich.it.by"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://bean.at16.agrinkevich.it.by  sites.xsd">
    <site url="http://it.by">
        <pages>
            <page title="Main page">
                <uri>/index</uri>
                <elements>
                    <element name="head">
                        head for main
                    </element>
                    <element name="body">
                        test for body
                    </element>
                </elements>
            </page>
            <page title="Login page">
                <uri>/login</uri>
                <elements>
                    <element name="head">
                        head for main
                    </element>
                    <element name="form">
                        form login
                    </element>
                </elements>
            </page>
        </pages>
    </site>
    <site url="http://ya.ru">
        <pages>
            <page title="Index page">
                <uri>/index</uri>
                <elements>
                    <element name="head">
                        Search yandex
                    </element>
                    <element name="form">
                        search form
                    </element>
                </elements>
            </page><page title="Search result page">
                <uri>/result</uri>
                <elements>
                    <element name="head">
                        Search result Yandex
                    </element>
                    <element name="content">
                        some content
                    </element>
                </elements>
            </page>
        </pages>
    </site>
</sites>

=== Alexandersimanovich/AT2019-03-12/src/by/it/vshchur/at15/sites+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<sites xmnls="http://bean.at16.shchur.it.by"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://bean.at16.shchur.it.by sites.xsd">
    <site url="http://it.by">
        <pages>
            <page title="Main page">
                <uri>/index</uri>
                <elements>
                    <element name="head">
                        head for main
                    </element>
                    <element name="body">
                        text for body
                    </element>
                </elements>
            </page>
            <page title="Login page">
                <uri>/index</uri>
                <elements>
                    <element name="head">
                        head for main
                    </element>
                    <element name="body">
                        text for body
                    </element>
                </elements>
            </page>
        </pages>
    </site>
    <site url="http://ya.ru">
        <pages>
            <page title="Index page">
                <uri>/index</uri>
                <elements>
                    <element name="head">
                        head for main
                    </element>
                    <element name="body">
                        text for body
                    </element>
                </elements>
            </page>
            <page title="Search result page">
                <uri>/index</uri>
                <elements>
                    <element name="head">
                        Search result Yandex
                    </element>
                    <element name="body">
                        some content
                    </element>
                </elements>
            </page>
        </pages>
    </site>
</sites>
